### ISSUE TITLE
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: -2

### ISSUE THREAD

**Issue by fdjomakon** [artur-tamazian/avro-schema-generator#6]
Using avro-schema-generator to generate schemas from Oracle Database Tables, I'm getting the following error at the code block: 
`String schemaJson = SchemaGenerator.generate(schema);`

Error:
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: -2
	at java.lang.AbstractStringBuilder.setLength(AbstractStringBuilder.java:207)
	at java.lang.StringBuilder.setLength(StringBuilder.java:76)
	at com.at.avro.formatters.SchemaFormatter.formatFields(SchemaFormatter.java:48)
	at com.at.avro.formatters.SchemaFormatter.toJson(SchemaFormatter.java:30)
	at com.at.avro.formatters.SchemaFormatter.toJson(SchemaFormatter.java:12)
	at com.at.avro.SchemaGenerator.generate(SchemaGenerator.java:22)
	at GenerateAvroSchema.main(GenerateAvroSchema.java:57)

Any idea what could be causing this ?

**Comment by artur-tamazian** [comment]
Looks like the AvroSchema that you pass to SchemaGenerator.generate() has no AvroFields.
Can you share the code you use to initialize it?

**Comment by fdjomakon** [comment]
Here it is, I have tried the first two code blocks you shared in the documentation but they were giving the same error :

```
import com.at.avro.AvroSchema;
import com.at.avro.DbSchemaExtractor;
import com.at.avro.SchemaGenerator;
import com.at.avro.config.AvroConfig;

public class GenerateAvroSchema {
    public static void main(String []args) {
        // Initialize db crawler that will create avro model objects
        DbSchemaExtractor schemaExtractor = new DbSchemaExtractor("jdbc:oracle:thin:@xxxxx:1521:SID", "user", "pass");

        AvroConfig avroConfig = new AvroConfig("com.boursorama.bi.raw");
        // Get avro models for a table
        AvroSchema schema = schemaExtractor.getForTable(avroConfig, "mydb_schema_name",  "mytable_name");
        System.out.println(schema.toString());
        String schemaJson = SchemaGenerator.generate(schema);
        System.out.println(schemaJson);
    }
}
```

I'm using ojdbc7 and have added us.fatehi:schemacrawler-oracle:14.14.02 to my maven dependencies.

**Comment by artur-tamazian** [comment]
The code you use looks good. So we need to collect more information about what happens.

 I would check the following:

- does it work with other tables? Maybe try doing getAll() instead of getForTable() and debug/print to see if any AvroSchema has fields in it.
- check if logs contain any suspicious warnings before the exception
- to really see what happens you should debug and set a breakpoint around line 23 in AvroSchema. You should check what table.getColumns() returns and what happens with them later.

Without debugging or having more information it's hard to say what's wrong. Hopefully, after finding the issue we'll be able to improve the library.

**Comment by artur-tamazian** [comment]
Closing for now. Let me know if you get more info on this.
