### ISSUE TITLE
Support for SQL array

### ISSUE THREAD

**Issue by eshepelyuk** [artur-tamazian/avro-schema-generator#7]
i have a table `my_table` with such sql declaring a field as pgsql array

```
....
 exclude_pm    | text[]                      |
....
```

Having java code

```
DbSchemaExtractor schemaExtractor = new DbSchemaExtractor("...", "...", "...")

AvroConfig avroConfig = new AvroConfig("ua.eshepelyuk")

List<AvroSchema> schemas = schemaExtractor.getForTables(avroConfig, "public", "my_table")

for (AvroSchema schema : schemas) {
  System.out.println(SchemaGenerator.generate(schema))
}
```

I receive exception

```
Caught: java.lang.IllegalArgumentException: unknown data type: _text
java.lang.IllegalArgumentException: unknown data type: _text
	at com.at.avro.config.AvroConfig.lambda$new$2(AvroConfig.java:30)
	at com.at.avro.AvroTypeUtil.getPrimitiveType(AvroTypeUtil.java:103)
	at com.at.avro.AvroTypeUtil.getAvroType(AvroTypeUtil.java:43)
	at com.at.avro.AvroField.<init>(AvroField.java:25)
	at com.at.avro.AvroSchema.<init>(AvroSchema.java:26)
	at com.at.avro.DbSchemaExtractor.get(DbSchemaExtractor.java:93)
	at com.at.avro.DbSchemaExtractor.getForTables(DbSchemaExtractor.java:57)
	at AvroGen.run(AvroGen.groovy:13)
```

**Comment by artur-tamazian** [comment]
Seems like text[] comes out as _text from schema crawler. The library doesn't know which avro type to use in this case. 

However, you can provide any custom mapping via AvroConfig. You can do it like this:

```java
AvroConfig avroConfig = new AvroConfig("ua.eshepelyuk")
  .setUnknownTypeResolver(type -> {
    // use "string" for "_type" columns
    if ("_text".equals(type)) return "string"; 

    // throw an exception for all other unknown types
    throw new IllegalArgumentException("unknown data type: " + type);           
});
```

**Comment by eshepelyuk** [comment]
Hello, 

1. I do doubt if this is a proper behaviour from `Schema Crawler`, to return `_text` , maybe that project need some contribution, I had not time to investigate ,so if you're sure on this - let me know
1.  if behaviour of `Schema Crawler` for handling `text[]` fields of `pgsql` is proper - then I do belive this should be handled natively by this project, as soon `json`, or other non ANSI SQL copatible `pgsql` types.

**Comment by artur-tamazian** [comment]
1.
Schema Crawler returns type "as is" (as provided by postgresql). Here's more information about it: https://www.postgresql.org/docs/9.3/xtypes.html, specifically:
> When you define a new base type, PostgreSQL automatically provides support for arrays of that type. The array type typically has the same name as the base type with the underscore character (_) prepended.

So basically the mapping would look like: 
```
_text -> {"type": "array", "items": "string"}
_int  -> {"type": "array", "items": "int"}
...
```


2.
Adding non-standard types support would be nice. This would require adding more sophisticated logic in DB -> avro type mapping. In order to do it well we would need to 

- define a list of databases we want to support their custom types for
- write mapping logic for each of them
- test this logic with each database

At the very beginning, I decided to not get into it and just provide the option to define any missing mapping when needed (the one mentioned in my previous message).

That said, now I think that adding one DB or even one type at a time is ok too.

**Comment by eshepelyuk** [comment]
Thanks for the explanation @artur-tamazian .
As for psql custom type support - my team is very interested in contributiong.
As soon as #8  will be accepted and released, we could proceed on this.

**Comment by eshepelyuk** [comment]
Hi, thanks for merging #15 
Do you have estimates for releasing this feature ?
